Strona rejestracji i logowania.
JustDunia/SoYummy pull request #11
Opened 2023-10-31 14:16 UTC by gabri3lt

Wrzucam zrobioną stronę rejestracji i logowania. Stylowanie narazie zrobiłem na szytwno ale podminię je na globalne. Póki co sprawdźcie czy to się dobrze zgrywa z całością i czy dobrze się u wszystkich wyświetla.

2023-10-31 18:30 UTC, JustDunia commented on SoYummy.SPA/src/components/RegisterForm/RegisterForm.module.css
Raczej robi się tak, że pisze się styl na minimalną szerokość ekranu i później kolejne media min-width. 
`@media (max-width: 767px) {
  .registerForm {
    width: 335px;
    height: 350px;
  }
}
@media (min-width: 768px) {
  .registerForm {
    width: 500px;
    height: 481px;
  }`
  Tutaj można byłoby wyrzucić max-width, a działałoby tak samo ;)

2023-10-31 18:36 UTC, JustDunia requested changes
Trzeba by dopracować wygląd na mniejszych ekranach. Na widoku na telefon napis Sign in wypada za obszar do rejestracji, a na większym ekranie jest wewnątrz tego obszaru. Na ekranie 320px ten obszar z inputami nie mieści się na ekranie.
![image](https://github.com/JustDunia/SoYummy/assets/109360997/e07a32d4-f6c7-41fc-a9ff-e7aedbd905f2)

Wysokość strony powinna być chyba na cały ekran. Na mniejszej rozdzielczości wygląda spoko, ale jak jest większa, to strona kończy się w połowie monitora.

Konsola wyrzuca błędy
![image](https://github.com/JustDunia/SoYummy/assets/109360997/ecd7d5a0-d552-4285-8e8c-82a1618fabaa)

Przydałaby się walidacja długości hasła. API wymaga minimum 8 znaków. Oczywiście możemy to zmienić na API, ale te 8 znaków to raczej standard.

2023-10-31 18:36 UTC, JustDunia commented on SoYummy.SPA/src/components/RegisterForm/RegisterForm.module.css
Raczej robi się tak, że pisze się styl na minimalną szerokość ekranu i później kolejne media min-width.
`@media (max-width: 767px) {
  .registerForm {
    width: 335px;
    height: 350px;
  }
}
@media (min-width: 768px) {
  .registerForm {
    width: 500px;
    height: 481px;
  }
}`
Tutaj można byłoby wyrzucić max-width, a działałoby tak samo ;)

2023-11-02 23:32 UTC, gabri3lt commented
Wrzuciłem poprawki i dodałem walidację do formularzy

2023-11-03 19:24 UTC, PPacuk reviewed
rozdzielczość 375
![obraz](https://github.com/JustDunia/SoYummy/assets/105542652/d0d64b15-24a2-488f-9dbd-b0795e93f29b)
rozdzielczość 649
![obraz](https://github.com/JustDunia/SoYummy/assets/105542652/8eb5b646-54b9-4106-ac8e-ab0bd9eadd2b)
makieta
![obraz](https://github.com/JustDunia/SoYummy/assets/105542652/3b08b617-6c4e-4e4d-97c6-2ae6de17e617)

ciemne tło jako backgroud w css rozciąga się razem z rozdzielczością i na każdym printscreen wygląda inaczej i nie zgadza się z układem na makiecie, może warto by było wrzucić to jako img w html i dać position absolute i bottom 0 żeby na każdym urządzeniu wyglądało to tak samo, wyświetla mi się również margin 8px z body, ale tutaj chyba tylko pomoże zrobienie jakiegoś wspólnego css na body i ogólne style

2023-11-04 10:38 UTC, PPacuk commented
Tak po przemyśleniu tego może też pomóc na tym co masz height:50vh ale tego nie sprawdzałem więc pokombinuj :)

2023-11-04 11:09 UTC, gabri3lt commented
Spoko, po kombinuję trochę i zobaczę co wyjdzie 😁

2023-11-07 21:35 UTC, closed without merging

2023-11-07 21:36 UTC, gabri3lt commented
Wersja nie nadająca się do merge. Będzie wrzucona poprawiona w nowym PR