I hope I didn't anything forgotten
JustDunia/SoYummy pull request #12
Opened 2023-10-31 19:00 UTC by magdalenajb

Niestety, ale nie wyświetlał mi się footer, gdy go pisałam. Z 3 razy w ogóle go poprawiałam. Mam nadzieję, że o niczym nie zapomniałam.

2023-10-31 20:17 UTC, JustDunia requested changes
Komponent Footer nie wyświetlał się, bo nigdzie nie był użyty. Trzeba umieścić go w SharedLayout.

Ale mimo umieszczenia go w odpowiednim miejscu strona nie działa, bo komponent Footer ma całą masę niezdefiniowanych elementów. Zaczęłam Ci je zaznaczać w komentarzach przy kodzie, ale jest ich znacznie więcej niż zaznaczyłam (spróbuj komendy npm run lint - pokażą Ci się wszystkie błędy)

Wszystkie zestawy komponent + module.css powinny być we wspólnych folderach, tak jak zrobiłaś DownFooter i SocialMedia

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/SubscribeForm.jsx
> +import c from "./SubscribeForm.css";
./SubscribeForm.module.css

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/SubscribeForm.jsx
> +import { useMedia } from "hooks";
skąd ten hook? Import nie działa, nie widać nic takiego jak "hooks"

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/index.js
Tego pliku można się całkowicie pozbyć

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/BenefitsList.jsx
Plik nazywa się BenefitsList, ale  exportuje komponent Preferences, wewnątrz którego używany jest BenefitsList (skąd on miałby być, skoro to jest plik BenefitsList.jsx?
W związku z tym elementy BenefitsList, Benefits i BenefitsText są undefined.

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/DownFooter/DownFooter.jsx
> +    <WrapperCopytight className={c.wrapper_copytight}>
Co to za komponent? Nie jest nigdzie zdefiniowany, więc wyrzuca błąd

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/DownFooter/DownFooter.jsx
> +      <TextCopyright className={c.text_copyright}>
jw.

2023-10-31 20:17 UTC, JustDunia commented on SoYummy.SPA/src/components/Footer/Footer.jsx
> +      <FooterConteiner className={c.footer_cointener}>
niezdefiniowany element

2023-11-02 14:04 UTC, dominikszajbler commented
w pullu były package.json i package-lock.json jako konflikty - chyba trzeba dodać do .gitignore

2023-11-03 06:13 UTC, dominikszajbler commented on SoYummy.SPA/package.json
plik konfliktował - ale w sumie nie wiem czy jego usunięcie będzie dobre

2023-11-03 06:15 UTC, dominikszajbler commented on SoYummy.SPA/package-lock.json
czy na pewno trzeba to importować

2023-11-08 16:52 UTC, closed without merging