Api   recipes
JustDunia/SoYummy pull request #13
Opened 2023-10-31 22:43 UTC by dominikszajbler

Dodałem api recipes - na razie tylko recipes/category-list Utwórz punkt końcowy, aby uzyskać listę kategorii. Teoretycznie wszystko jest poprawnie ale zamiast listy kategorii zwraca pusty []. Proszę o analizę

2023-11-01 13:37 UTC, JustDunia requested changes

2023-11-01 13:37 UTC, JustDunia commented on SoYummy.API/models/recipe.js
> +const Recipe = model('Recipe', recipeSchema);
Pusta tablica pokazywała się dlatego, że nie powiązałeś swojego modelu Recipe z istniejącą kolekcją 'Recipes'.
Wystarczy dodać tą referencję i wszystko działa.
`const Recipe = model('Recipe', recipeSchema, 'Recipes')`

2023-11-01 16:11 UTC, dominikszajbler commented on SoYummy.API/models/recipe.js
> +const Recipe = model('Recipe', recipeSchema);
poprawiono

2023-11-01 20:09 UTC, dominikszajbler reviewed
teoretycznie wszystko działa - niestety u mnie zwraca zamiast recipes wg modelu pustą tablicę [], proszę o sprawdzenie

2023-11-02 09:55 UTC, dominikszajbler commented
Przy wyszukiwaniu przepisów po ID nastąpiła nieprawidłowość z routerami. Wg kolejności przy zapytaniu
localhost:3000/recipes/konkretne_id_przepisu zwracał pustą tablicę , bo wcześniejszy router w  miejscu localhost:3000/recipes/??? miał zdefiniowane wyszukiwanie po :category. W związku z tym zaimplementowałem ścieżkę dla wyszukiwania po id takim układzie
/recipes/id/:id dla identyfikatorów. Czyli zapytanie będzie musiało wyglądać tak:
localhost:3000/recipes/id/konkretne_id_przepisu

2023-11-04 13:58 UTC, merged